// lib/presentation/pages/pages.dart
export 'auth/login_page.dart';
export 'clientes/clientes_page.dart';
export 'dashboard/dashboard_page.dart';
export 'home_page.dart';
export 'pedidos/detalhe_pedido_page.dart';
export 'pedidos/pedido_detalhe_modal.dart';
export 'pedidos/pedidos_page.dart';
export 'produtos/produtos_page.dart';
export 'splash_page.dart';
export 'tenants/tenants_page.dart';
export 'tenants/detalhe_tenant_page.dart';
export 'tenants/form_tenant_page.dart';
